name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # push 到 master 分支时触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 使用 GitHub 提供的 Checkout action 检出代码

      - name: Install dependencies
        run: npm install # 安装依赖

      - name: Build
        run: npm run build # 构建

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3 # 使用 GitHub 提供的 Deploy action 部署页面
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # 要部署的文件夹路径
